services:
  servicofaturamento-db:
    image: postgres:18
    networks:
      - servicofaturamento-network
    container_name: servicofaturamento-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=servicofaturamento
    ports:
      - 5490:5432
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - servicofaturamento-db-data:/var/lib/postgresql
    restart: always

volumes:
  servicofaturamento-db-data:
    name: servicofaturamento-db-data

networks:
  servicofaturamento-network:
    driver: bridge